[twooutputs]
input_path = "./data/augmented_spot_patches.h5"
output_path = "./serverdaten/twooutput"

[oneoutput]
input_path = "./data/augmented_spot_patches.h5"
output_path = "./serverdaten/oneoutput"

[pin]
input_path = "./data/augmented_spot_patches.h5"
output_path = "./output/pin"
